### ISSUE TITLE
# Raytheon corrected RPC file directory?

### ISSUE THREAD

**Issue by Calsia** [Kitware/Danesfield#35]
In `input.ini`, there is a parameter named `rpc_dir`. how can i get this file？
thans for any response.

**Comment by Calsia** [comment]
![image](https://user-images.githubusercontent.com/13194457/150743504-219b62ed-8325-4655-9ee6-18f923fb4a32.png)

**Comment by mleotta** [comment]
`rpc_dir` should be optional.  It's only used when running Danesfield with a proprietary software alternative to the VisSat pipeline for computing point clouds from satellite images.  That other software also estimates corrected RPC projection models that replace the models found in the image headers.  VisSat currently does not.  If `rpc_dir` is not used we stick with the original RPC parameters that come with the images.

**Comment by Calsia** [comment]
That is to say, using vissat, I can directly set it to 'None', right?

**Comment by Calsia** [comment]
> `rpc_dir` should be optional. It's only used when running Danesfield with a proprietary software alternative to the VisSat pipeline for computing point clouds from satellite images. That other software also estimates corrected RPC projection models that replace the models found in the image headers. VisSat currently does not. If `rpc_dir` is not used we stick with the original RPC parameters that come with the images.

I was just curious before, why do you need an extra file when you already have it in the image headers

**Comment by mleotta** [comment]
I believe just not including (e.g. commenting out) that `rpc_dir` is what you want.  Setting it to `None` may work, but I haven't checked if that string "None" would be parse into a Python `None` or not.

This is needed because some tools can optimize the RPC values found in the image headers to get better results.  We treat the input images as read-only so we don't want to write these value back to the image headers.  Instead we write this metadata into optional sidecar files that taken precedence over the header data, if provided.

**Comment by Calsia** [comment]
Thanks  for all the help on this and your responsiveness.
